-- Migration: add 107 missing countries (with ISO-2, ISO-3 and currency codes)
-- All entries that appear in the ExchangeRate-API but were absent from the countries table.
-- Uses ON CONFLICT (iso2) DO NOTHING so re-running is safe.

INSERT INTO countries (country_name, iso2, short_code, country_code, currency_code, dialing_code, is_active)
VALUES
  ('Afghanistan', 'AF', 'AFG', 'AFG', 'AFN', '+93', true),
  ('Albania', 'AL', 'ALB', 'ALB', 'ALL', '+355', true),
  ('Algeria', 'DZ', 'DZA', 'DZA', 'DZD', '+213', true),
  ('Angola', 'AO', 'AGO', 'AGO', 'AOA', '+244', true),
  ('Argentina', 'AR', 'ARG', 'ARG', 'ARS', '+54', true),
  ('Armenia', 'AM', 'ARM', 'ARM', 'AMD', '+374', true),
  ('Azerbaijan', 'AZ', 'AZE', 'AZE', 'AZN', '+994', true),
  ('Bahamas', 'BS', 'BHS', 'BHS', 'BSD', '+1-242', true),
  ('Barbados', 'BB', 'BRB', 'BRB', 'BBD', '+1-246', true),
  ('Belarus', 'BY', 'BLR', 'BLR', 'BYN', '+375', true),
  ('Belize', 'BZ', 'BLZ', 'BLZ', 'BZD', '+501', true),
  ('Bhutan', 'BT', 'BTN', 'BTN', 'BTN', '+975', true),
  ('Bolivia', 'BO', 'BOL', 'BOL', 'BOB', '+591', true),
  ('Bosnia and Herzegovina', 'BA', 'BIH', 'BIH', 'BAM', '+387', true),
  ('Botswana', 'BW', 'BWA', 'BWA', 'BWP', '+267', true),
  ('Brazil', 'BR', 'BRA', 'BRA', 'BRL', '+55', true),
  ('Brunei', 'BN', 'BRN', 'BRN', 'BND', '+673', true),
  ('Burundi', 'BI', 'BDI', 'BDI', 'BIF', '+257', true),
  ('Cambodia', 'KH', 'KHM', 'KHM', 'KHR', '+855', true),
  ('Canada', 'CA', 'CAN', 'CAN', 'CAD', '+1', true),
  ('Cape Verde', 'CV', 'CPV', 'CPV', 'CVE', '+238', true),
  ('Chile', 'CL', 'CHL', 'CHL', 'CLP', '+56', true),
  ('Colombia', 'CO', 'COL', 'COL', 'COP', '+57', true),
  ('Comoros', 'KM', 'COM', 'COM', 'KMF', '+269', true),
  ('Costa Rica', 'CR', 'CRI', 'CRI', 'CRC', '+506', true),
  ('Cuba', 'CU', 'CUB', 'CUB', 'CUP', '+53', true),
  ('DR Congo', 'CD', 'COD', 'COD', 'CDF', '+243', true),
  ('Djibouti', 'DJ', 'DJI', 'DJI', 'DJF', '+253', true),
  ('Dominican Republic', 'DO', 'DOM', 'DOM', 'DOP', '+1-809', true),
  ('Egypt', 'EG', 'EGY', 'EGY', 'EGP', '+20', true),
  ('Eritrea', 'ER', 'ERI', 'ERI', 'ERN', '+291', true),
  ('Eswatini', 'SZ', 'SWZ', 'SWZ', 'SZL', '+268', true),
  ('Ethiopia', 'ET', 'ETH', 'ETH', 'ETB', '+251', true),
  ('Fiji', 'FJ', 'FJI', 'FJI', 'FJD', '+679', true),
  ('Gambia', 'GM', 'GMB', 'GMB', 'GMD', '+220', true),
  ('Georgia', 'GE', 'GEO', 'GEO', 'GEL', '+995', true),
  ('Ghana', 'GH', 'GHA', 'GHA', 'GHS', '+233', true),
  ('Guatemala', 'GT', 'GTM', 'GTM', 'GTQ', '+502', true),
  ('Guinea', 'GN', 'GIN', 'GIN', 'GNF', '+224', true),
  ('Guyana', 'GY', 'GUY', 'GUY', 'GYD', '+592', true),
  ('Haiti', 'HT', 'HTI', 'HTI', 'HTG', '+509', true),
  ('Honduras', 'HN', 'HND', 'HND', 'HNL', '+504', true),
  ('Hong Kong', 'HK', 'HKG', 'HKG', 'HKD', '+852', true),
  ('Iran', 'IR', 'IRN', 'IRN', 'IRR', '+98', true),
  ('Iraq', 'IQ', 'IRQ', 'IRQ', 'IQD', '+964', true),
  ('Israel', 'IL', 'ISR', 'ISR', 'ILS', '+972', true),
  ('Jamaica', 'JM', 'JAM', 'JAM', 'JMD', '+1-876', true),
  ('Jordan', 'JO', 'JOR', 'JOR', 'JOD', '+962', true),
  ('Kazakhstan', 'KZ', 'KAZ', 'KAZ', 'KZT', '+7', true),
  ('Kenya', 'KE', 'KEN', 'KEN', 'KES', '+254', true),
  ('Kyrgyzstan', 'KG', 'KGZ', 'KGZ', 'KGS', '+996', true),
  ('Laos', 'LA', 'LAO', 'LAO', 'LAK', '+856', true),
  ('Lebanon', 'LB', 'LBN', 'LBN', 'LBP', '+961', true),
  ('Lesotho', 'LS', 'LSO', 'LSO', 'LSL', '+266', true),
  ('Liberia', 'LR', 'LBR', 'LBR', 'LRD', '+231', true),
  ('Libya', 'LY', 'LBY', 'LBY', 'LYD', '+218', true),
  ('Macao', 'MO', 'MAC', 'MAC', 'MOP', '+853', true),
  ('Madagascar', 'MG', 'MDG', 'MDG', 'MGA', '+261', true),
  ('Malawi', 'MW', 'MWI', 'MWI', 'MWK', '+265', true),
  ('Maldives', 'MV', 'MDV', 'MDV', 'MVR', '+960', true),
  ('Mauritania', 'MR', 'MRT', 'MRT', 'MRU', '+222', true),
  ('Mauritius', 'MU', 'MUS', 'MUS', 'MUR', '+230', true),
  ('Mexico', 'MX', 'MEX', 'MEX', 'MXN', '+52', true),
  ('Moldova', 'MD', 'MDA', 'MDA', 'MDL', '+373', true),
  ('Mongolia', 'MN', 'MNG', 'MNG', 'MNT', '+976', true),
  ('Morocco', 'MA', 'MAR', 'MAR', 'MAD', '+212', true),
  ('Mozambique', 'MZ', 'MOZ', 'MOZ', 'MZN', '+258', true),
  ('Myanmar', 'MM', 'MMR', 'MMR', 'MMK', '+95', true),
  ('Namibia', 'NA', 'NAM', 'NAM', 'NAD', '+264', true),
  ('Nicaragua', 'NI', 'NIC', 'NIC', 'NIO', '+505', true),
  ('Nigeria', 'NG', 'NGA', 'NGA', 'NGN', '+234', true),
  ('North Macedonia', 'MK', 'MKD', 'MKD', 'MKD', '+389', true),
  ('Panama', 'PA', 'PAN', 'PAN', 'PAB', '+507', true),
  ('Papua New Guinea', 'PG', 'PNG', 'PNG', 'PGK', '+675', true),
  ('Paraguay', 'PY', 'PRY', 'PRY', 'PYG', '+595', true),
  ('Peru', 'PE', 'PER', 'PER', 'PEN', '+51', true),
  ('Russia', 'RU', 'RUS', 'RUS', 'RUB', '+7', true),
  ('Rwanda', 'RW', 'RWA', 'RWA', 'RWF', '+250', true),
  ('Samoa', 'WS', 'WSM', 'WSM', 'WST', '+685', true),
  ('Serbia', 'RS', 'SRB', 'SRB', 'RSD', '+381', true),
  ('Seychelles', 'SC', 'SYC', 'SYC', 'SCR', '+248', true),
  ('Sierra Leone', 'SL', 'SLE', 'SLE', 'SLE', '+232', true),
  ('Solomon Islands', 'SB', 'SLB', 'SLB', 'SBD', '+677', true),
  ('Somalia', 'SO', 'SOM', 'SOM', 'SOS', '+252', true),
  ('South Africa', 'ZA', 'ZAF', 'ZAF', 'ZAR', '+27', true),
  ('South Sudan', 'SS', 'SSD', 'SSD', 'SSP', '+211', true),
  ('Sudan', 'SD', 'SDN', 'SDN', 'SDG', '+249', true),
  ('Suriname', 'SR', 'SUR', 'SUR', 'SRD', '+597', true),
  ('Syria', 'SY', 'SYR', 'SYR', 'SYP', '+963', true),
  ('São Tomé and Príncipe', 'ST', 'STP', 'STP', 'STN', '+239', true),
  ('Taiwan', 'TW', 'TWN', 'TWN', 'TWD', '+886', true),
  ('Tajikistan', 'TJ', 'TJK', 'TJK', 'TJS', '+992', true),
  ('Tanzania', 'TZ', 'TZA', 'TZA', 'TZS', '+255', true),
  ('Tonga', 'TO', 'TON', 'TON', 'TOP', '+676', true),
  ('Trinidad and Tobago', 'TT', 'TTO', 'TTO', 'TTD', '+1-868', true),
  ('Tunisia', 'TN', 'TUN', 'TUN', 'TND', '+216', true),
  ('Turkey', 'TR', 'TUR', 'TUR', 'TRY', '+90', true),
  ('Turkmenistan', 'TM', 'TKM', 'TKM', 'TMT', '+993', true),
  ('Uganda', 'UG', 'UGA', 'UGA', 'UGX', '+256', true),
  ('Ukraine', 'UA', 'UKR', 'UKR', 'UAH', '+380', true),
  ('Uruguay', 'UY', 'URY', 'URY', 'UYU', '+598', true),
  ('Uzbekistan', 'UZ', 'UZB', 'UZB', 'UZS', '+998', true),
  ('Vanuatu', 'VU', 'VUT', 'VUT', 'VUV', '+678', true),
  ('Venezuela', 'VE', 'VEN', 'VEN', 'VES', '+58', true),
  ('Yemen', 'YE', 'YEM', 'YEM', 'YER', '+967', true),
  ('Zambia', 'ZM', 'ZMB', 'ZMB', 'ZMW', '+260', true),
  ('Zimbabwe', 'ZW', 'ZWE', 'ZWE', 'ZWG', '+263', true)
ON CONFLICT (iso2) DO NOTHING;

