-- Gifts & Celebrations category tree
-- 1 L1, 64 L2 sub-categories (each with 8-digit HSN), 192 L3 product types (3 per L2)
-- L3 slugs scoped "<type>-in-<l2>" per categories_slug_unique convention.

BEGIN;

-- ── L1 ──────────────────────────────────────────────────────────────
INSERT INTO public.categories (name, slug, parent_id, level, display_order, is_active)
VALUES ('Gifts & Celebrations', 'gifts-celebrations', NULL, 1, 24, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.category_hsn_codes (category_slug, hsn_code, description)
VALUES ('gifts-celebrations', '48239099', 'Gifts & Celebrations')
ON CONFLICT (category_slug) DO NOTHING;

-- ── L2 sub-categories + HSN (8-digit) ───────────────────────────────
WITH l1 AS (SELECT id FROM public.categories WHERE slug = 'gifts-celebrations'),
l2_data(name, slug, display_order, hsn_code) AS (VALUES
  ('Gift Hampers',                 'gift-hampers',                 1,  '39249090'),
  ('Personalized Gifts',           'personalized-gifts',             2,  '39269099'),
  ('Flowers & Bouquets',           'flowers-bouquets',               3,  '06031900'),
  ('Chocolates & Sweets',          'chocolates-sweets',              4,  '18069090'),
  ('Cakes & Desserts',             'cakes-desserts',                 5,  '19059090'),
  ('Gift Boxes',                   'gift-boxes',                     6,  '48239099'),
  ('Corporate Gifts',              'corporate-gifts',                7,  '48239099'),
  ('Festival Gifts',               'festival-gifts',                 8,  '95059090'),
  ('Greeting Cards',               'greeting-cards',                 9,  '48209090'),
  ('Soft Toys',                    'soft-toys',                      10, '95030099'),
  ('Home Décor Gifts',             'home-decor-gifts',               11, '83062900'),
  ('Jewelry Gifts',                'jewelry-gifts',                  12, '71179090'),
  ('Beauty & Wellness Gifts',      'beauty-wellness-gifts',          13, '33049990'),
  ('Toys & Kids Gifts',            'toys-kids-gifts',                14, '95030099'),
  ('Party Supplies',               'party-supplies',                 15, '95059090'),
  ('Gift Vouchers',                'gift-vouchers',                  16, '49119990'),
  ('Dry Fruit Gifts',              'dry-fruit-gifts',                17, '08029090'),
  ('Gourmet Gifts',                'gourmet-gifts',                  18, '21069099'),
  ('Tea & Coffee Gifts',           'tea-coffee-gifts',               19, '09023000'),
  ('Stationery Gifts',             'stationery-gifts',               20, '48201000'),
  ('Religious Gifts',              'religious-gifts',                21, '83062110'),
  ('Baby Gifts',                   'baby-gifts',                     22, '96190010'),
  ('Wedding Gifts',                'wedding-gifts',                  23, '48239099'),
  ('Anniversary Gifts',            'anniversary-gifts',              24, '48239099'),
  ('Birthday Gifts',               'birthday-gifts',                 25, '48239099'),
  ('Luxury Gifts',                 'luxury-gifts',                   26, '48239099'),
  ('Eco-Friendly Gifts',           'eco-friendly-gifts',             27, '39269099'),
  ('Handmade Gifts',               'handmade-gifts',                 28, '48239099'),
  ('Experience Gifts',             'experience-gifts',               29, '49119990'),
  ('Seasonal Gifts',               'seasonal-gifts',                 30, '48239099'),
  ('Thank You Gifts',              'thank-you-gifts',                31, '48239099'),
  ('Housewarming Gifts',           'housewarming-gifts',             32, '94036000'),
  ('Retirement Gifts',             'retirement-gifts',               33, '48239099'),
  ('Graduation Gifts',             'graduation-gifts',               34, '48201000'),
  ('Get Well Soon Gifts',          'get-well-soon-gifts',            35, '33049990'),
  ('Friendship Gifts',             'friendship-gifts',               36, '48239099'),
  ('Valentine Gifts',              'valentine-gifts',                37, '71179090'),
  ('Mother''s Day Gifts',          'mothers-day-gifts',              38, '48239099'),
  ('Father''s Day Gifts',          'fathers-day-gifts',              39, '48239099'),
  ('Christmas Gifts',              'christmas-gifts',                40, '95051000'),
  ('New Year Gifts',               'new-year-gifts',                 41, '95059090'),
  ('Eid Gifts',                    'eid-gifts',                      42, '21069099'),
  ('Diwali Gifts',                 'diwali-gifts',                   43, '95059090'),
  ('Rakhi Gifts',                  'rakhi-gifts',                    44, '71179090'),
  ('Corporate Merchandise',        'corporate-merchandise',          45, '48201000'),
  ('Gift Baskets',                 'gift-baskets',                   46, '39249090'),
  ('Surprise Gifts',               'surprise-gifts',                 47, '48239099'),
  ('Collectible Gifts',            'collectible-gifts',              48, '97060000'),
  ('Pet Gifts',                    'pet-gifts',                      49, '23091000'),
  ('Travel Gifts',                 'travel-gifts',                   50, '42029200'),
  ('Tech Gifts',                   'tech-gifts',                     51, '85177990'),
  ('Fashion Accessories Gifts',    'fashion-accessories-gifts',      52, '42029200'),
  ('Kitchen & Dining Gifts',       'kitchen-dining-gifts',           53, '69120090'),
  ('Books & Hobby Gifts',          'books-hobby-gifts',              54, '49019900'),
  ('Wellness Hampers',             'wellness-hampers',               55, '33049990'),
  ('Luxury Hampers',               'luxury-hampers',                 56, '39249090'),
  ('Snack Hampers',                'snack-hampers',                  57, '21069099'),
  ('Chocolate Hampers',            'chocolate-hampers',              58, '18069090'),
  ('Fruit Baskets',                'fruit-baskets',                  59, '08045000'),
  ('Flower Arrangements',          'flower-arrangements',            60, '06031900'),
  ('Gift Sets',                    'gift-sets',                      61, '39249090'),
  ('Keepsakes & Souvenirs',        'keepsakes-souvenirs',            62, '97060000'),
  ('Personalized Accessories',     'personalized-accessories',       63, '71179090'),
  ('Event & Celebration Supplies', 'event-celebration-supplies',     64, '95059090')
)
INSERT INTO public.categories (name, slug, parent_id, level, display_order, is_active)
SELECT d.name, d.slug, l1.id, 2, d.display_order, true
FROM l2_data d, l1
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.category_hsn_codes (category_slug, hsn_code, description)
SELECT slug, hsn_code, name
FROM (VALUES
  ('gift-hampers',                 '39249090', 'Gift Hampers'),
  ('personalized-gifts',           '39269099', 'Personalized Gifts'),
  ('flowers-bouquets',             '06031900', 'Flowers & Bouquets'),
  ('chocolates-sweets',            '18069090', 'Chocolates & Sweets'),
  ('cakes-desserts',               '19059090', 'Cakes & Desserts'),
  ('gift-boxes',                   '48239099', 'Gift Boxes'),
  ('corporate-gifts',              '48239099', 'Corporate Gifts'),
  ('festival-gifts',               '95059090', 'Festival Gifts'),
  ('greeting-cards',               '48209090', 'Greeting Cards'),
  ('soft-toys',                    '95030099', 'Soft Toys'),
  ('home-decor-gifts',             '83062900', 'Home Décor Gifts'),
  ('jewelry-gifts',                '71179090', 'Jewelry Gifts'),
  ('beauty-wellness-gifts',        '33049990', 'Beauty & Wellness Gifts'),
  ('toys-kids-gifts',              '95030099', 'Toys & Kids Gifts'),
  ('party-supplies',               '95059090', 'Party Supplies'),
  ('gift-vouchers',                '49119990', 'Gift Vouchers'),
  ('dry-fruit-gifts',              '08029090', 'Dry Fruit Gifts'),
  ('gourmet-gifts',                '21069099', 'Gourmet Gifts'),
  ('tea-coffee-gifts',             '09023000', 'Tea & Coffee Gifts'),
  ('stationery-gifts',             '48201000', 'Stationery Gifts'),
  ('religious-gifts',              '83062110', 'Religious Gifts'),
  ('baby-gifts',                   '96190010', 'Baby Gifts'),
  ('wedding-gifts',                '48239099', 'Wedding Gifts'),
  ('anniversary-gifts',            '48239099', 'Anniversary Gifts'),
  ('birthday-gifts',               '48239099', 'Birthday Gifts'),
  ('luxury-gifts',                 '48239099', 'Luxury Gifts'),
  ('eco-friendly-gifts',           '39269099', 'Eco-Friendly Gifts'),
  ('handmade-gifts',               '48239099', 'Handmade Gifts'),
  ('experience-gifts',             '49119990', 'Experience Gifts'),
  ('seasonal-gifts',               '48239099', 'Seasonal Gifts'),
  ('thank-you-gifts',              '48239099', 'Thank You Gifts'),
  ('housewarming-gifts',           '94036000', 'Housewarming Gifts'),
  ('retirement-gifts',             '48239099', 'Retirement Gifts'),
  ('graduation-gifts',             '48201000', 'Graduation Gifts'),
  ('get-well-soon-gifts',          '33049990', 'Get Well Soon Gifts'),
  ('friendship-gifts',             '48239099', 'Friendship Gifts'),
  ('valentine-gifts',              '71179090', 'Valentine Gifts'),
  ('mothers-day-gifts',            '48239099', 'Mother''s Day Gifts'),
  ('fathers-day-gifts',            '48239099', 'Father''s Day Gifts'),
  ('christmas-gifts',              '95051000', 'Christmas Gifts'),
  ('new-year-gifts',               '95059090', 'New Year Gifts'),
  ('eid-gifts',                    '21069099', 'Eid Gifts'),
  ('diwali-gifts',                 '95059090', 'Diwali Gifts'),
  ('rakhi-gifts',                  '71179090', 'Rakhi Gifts'),
  ('corporate-merchandise',        '48201000', 'Corporate Merchandise'),
  ('gift-baskets',                 '39249090', 'Gift Baskets'),
  ('surprise-gifts',               '48239099', 'Surprise Gifts'),
  ('collectible-gifts',            '97060000', 'Collectible Gifts'),
  ('pet-gifts',                    '23091000', 'Pet Gifts'),
  ('travel-gifts',                 '42029200', 'Travel Gifts'),
  ('tech-gifts',                   '85177990', 'Tech Gifts'),
  ('fashion-accessories-gifts',    '42029200', 'Fashion Accessories Gifts'),
  ('kitchen-dining-gifts',         '69120090', 'Kitchen & Dining Gifts'),
  ('books-hobby-gifts',            '49019900', 'Books & Hobby Gifts'),
  ('wellness-hampers',             '33049990', 'Wellness Hampers'),
  ('luxury-hampers',               '39249090', 'Luxury Hampers'),
  ('snack-hampers',                '21069099', 'Snack Hampers'),
  ('chocolate-hampers',            '18069090', 'Chocolate Hampers'),
  ('fruit-baskets',                '08045000', 'Fruit Baskets'),
  ('flower-arrangements',          '06031900', 'Flower Arrangements'),
  ('gift-sets',                    '39249090', 'Gift Sets'),
  ('keepsakes-souvenirs',          '97060000', 'Keepsakes & Souvenirs'),
  ('personalized-accessories',     '71179090', 'Personalized Accessories'),
  ('event-celebration-supplies',   '95059090', 'Event & Celebration Supplies')
) AS v(slug, hsn_code, name)
ON CONFLICT (category_slug) DO NOTHING;

-- ── L3 product types (3 per L2 = 192 rows) ──────────────────────────
WITH l2 AS (
  SELECT id, slug
  FROM public.categories
  WHERE level = 2
    AND parent_id = (SELECT id FROM public.categories WHERE slug = 'gifts-celebrations')
),
types(l2_slug, name, base_slug, display_order) AS (VALUES
  ('gift-hampers',                 'Assorted Hamper',              'assorted-hamper',              1),
  ('gift-hampers',                 'Premium Hamper',               'premium-hamper',               2),
  ('gift-hampers',                 'Luxury Hamper',                'luxury-hamper',                3),
  ('personalized-gifts',           'Customized Mug',               'customized-mug',               1),
  ('personalized-gifts',           'Photo Frame',                  'photo-frame',                  2),
  ('personalized-gifts',           'Name Plaque',                  'name-plaque',                  3),
  ('flowers-bouquets',             'Rose Bouquet',                 'rose-bouquet',                 1),
  ('flowers-bouquets',             'Mixed Flower Bouquet',         'mixed-flower-bouquet',         2),
  ('flowers-bouquets',             'Orchid Bouquet',               'orchid-bouquet',               3),
  ('chocolates-sweets',            'Chocolate Box',                'chocolate-box',                1),
  ('chocolates-sweets',            'Truffle Collection',           'truffle-collection',           2),
  ('chocolates-sweets',            'Sweet Box',                    'sweet-box',                    3),
  ('cakes-desserts',               'Birthday Cake',                'birthday-cake',                1),
  ('cakes-desserts',               'Cupcakes',                     'cupcakes',                     2),
  ('cakes-desserts',               'Brownies',                     'brownies',                     3),
  ('gift-boxes',                   'Luxury Gift Box',              'luxury-gift-box',              1),
  ('gift-boxes',                   'Surprise Gift Box',            'surprise-gift-box',            2),
  ('gift-boxes',                   'Curated Gift Box',             'curated-gift-box',             3),
  ('corporate-gifts',              'Executive Gift Set',           'executive-gift-set',           1),
  ('corporate-gifts',              'Office Gift Box',              'office-gift-box',              2),
  ('corporate-gifts',              'Business Gift Hamper',         'business-gift-hamper',         3),
  ('festival-gifts',               'Festival Hamper',              'festival-hamper',              1),
  ('festival-gifts',               'Celebration Gift Box',         'celebration-gift-box',         2),
  ('festival-gifts',               'Seasonal Gift Set',            'seasonal-gift-set',            3),
  ('greeting-cards',               'Birthday Card',                'birthday-card',                1),
  ('greeting-cards',               'Anniversary Card',             'anniversary-card',             2),
  ('greeting-cards',               'Thank You Card',               'thank-you-card',               3),
  ('soft-toys',                    'Teddy Bear',                   'teddy-bear',                   1),
  ('soft-toys',                    'Plush Toy',                    'plush-toy',                    2),
  ('soft-toys',                    'Stuffed Animal',               'stuffed-animal',               3),
  ('home-decor-gifts',             'Decorative Showpiece',         'decorative-showpiece',         1),
  ('home-decor-gifts',             'Wall Art',                     'wall-art',                     2),
  ('home-decor-gifts',             'Candle Set',                   'candle-set',                   3),
  ('jewelry-gifts',                'Necklace Set',                 'necklace-set',                 1),
  ('jewelry-gifts',                'Bracelet',                     'bracelet',                     2),
  ('jewelry-gifts',                'Earrings Set',                 'earrings-set',                 3),
  ('beauty-wellness-gifts',        'Skincare Set',                 'skincare-set',                 1),
  ('beauty-wellness-gifts',        'Spa Kit',                      'spa-kit',                      2),
  ('beauty-wellness-gifts',        'Grooming Kit',                 'grooming-kit',                 3),
  ('toys-kids-gifts',              'Educational Toy',              'educational-toy',              1),
  ('toys-kids-gifts',              'Activity Kit',                 'activity-kit',                 2),
  ('toys-kids-gifts',              'Toy Gift Set',                 'toy-gift-set',                 3),
  ('party-supplies',               'Balloon Set',                  'balloon-set',                  1),
  ('party-supplies',               'Decoration Kit',               'decoration-kit',               2),
  ('party-supplies',               'Party Pack',                   'party-pack',                   3),
  ('gift-vouchers',                'Physical Gift Card',           'physical-gift-card',           1),
  ('gift-vouchers',                'Digital Gift Card',            'digital-gift-card',            2),
  ('gift-vouchers',                'Branded Gift Certificate',     'branded-gift-certificate',     3),
  ('dry-fruit-gifts',              'Dry Fruit Box',                'dry-fruit-box',                1),
  ('dry-fruit-gifts',              'Premium Dry Fruit Hamper',     'premium-dry-fruit-hamper',     2),
  ('dry-fruit-gifts',              'Mixed Nut Gift Box',           'mixed-nut-gift-box',           3),
  ('gourmet-gifts',                'Gourmet Basket',               'gourmet-basket',               1),
  ('gourmet-gifts',                'Imported Food Gift Set',       'imported-food-gift-set',       2),
  ('gourmet-gifts',                'Artisan Food Hamper',          'artisan-food-hamper',          3),
  ('tea-coffee-gifts',             'Tea Gift Set',                 'tea-gift-set',                 1),
  ('tea-coffee-gifts',             'Coffee Gift Box',              'coffee-gift-box',              2),
  ('tea-coffee-gifts',             'Tea & Coffee Combo',           'tea-coffee-combo',             3),
  ('stationery-gifts',             'Premium Pen Set',              'premium-pen-set',              1),
  ('stationery-gifts',             'Journal Set',                  'journal-set',                  2),
  ('stationery-gifts',             'Desk Gift Set',                'desk-gift-set',                3),
  ('religious-gifts',              'Idol',                         'idol',                         1),
  ('religious-gifts',              'Prayer Kit',                   'prayer-kit',                   2),
  ('religious-gifts',              'Spiritual Gift Set',           'spiritual-gift-set',           3),
  ('baby-gifts',                   'Baby Care Kit',                'baby-care-kit',                1),
  ('baby-gifts',                   'Newborn Gift Set',             'newborn-gift-set',             2),
  ('baby-gifts',                   'Baby Essentials Hamper',       'baby-essentials-hamper',       3),
  ('wedding-gifts',                'Wedding Hamper',               'wedding-hamper',               1),
  ('wedding-gifts',                'Couple Gift Set',              'couple-gift-set',              2),
  ('wedding-gifts',                'Bridal Gift Box',              'bridal-gift-box',              3),
  ('anniversary-gifts',            'Couple Gift Box',              'couple-gift-box',              1),
  ('anniversary-gifts',            'Anniversary Hamper',           'anniversary-hamper',           2),
  ('anniversary-gifts',            'Romantic Gift Set',            'romantic-gift-set',            3),
  ('birthday-gifts',               'Birthday Hamper',              'birthday-hamper',              1),
  ('birthday-gifts',               'Birthday Gift Box',            'birthday-gift-box',            2),
  ('birthday-gifts',               'Birthday Celebration Set',     'birthday-celebration-set',     3),
  ('luxury-gifts',                 'Luxury Hamper',                'luxury-hamper',                1),
  ('luxury-gifts',                 'Premium Collection',           'premium-collection',           2),
  ('luxury-gifts',                 'Executive Luxury Set',         'executive-luxury-set',         3),
  ('eco-friendly-gifts',           'Sustainable Gift Set',         'sustainable-gift-set',         1),
  ('eco-friendly-gifts',           'Bamboo Gift Box',              'bamboo-gift-box',              2),
  ('eco-friendly-gifts',           'Eco Hamper',                   'eco-hamper',                   3),
  ('handmade-gifts',               'Handcrafted Gift Box',         'handcrafted-gift-box',         1),
  ('handmade-gifts',               'Artisan Gift Set',             'artisan-gift-set',             2),
  ('handmade-gifts',               'Craft Hamper',                 'craft-hamper',                 3),
  ('experience-gifts',             'Experience Voucher',           'experience-voucher',           1),
  ('experience-gifts',             'Activity Gift Card',           'activity-gift-card',           2),
  ('experience-gifts',             'Adventure Gift Pass',          'adventure-gift-pass',          3),
  ('seasonal-gifts',               'Summer Gift Box',              'summer-gift-box',              1),
  ('seasonal-gifts',               'Winter Gift Collection',       'winter-gift-collection',       2),
  ('seasonal-gifts',               'Seasonal Hamper',              'seasonal-hamper',              3),
  ('thank-you-gifts',              'Appreciation Gift Box',        'appreciation-gift-box',        1),
  ('thank-you-gifts',              'Thank You Hamper',             'thank-you-hamper',             2),
  ('thank-you-gifts',              'Gratitude Gift Set',           'gratitude-gift-set',           3),
  ('housewarming-gifts',           'Home Essentials Set',          'home-essentials-set',          1),
  ('housewarming-gifts',           'Housewarming Hamper',          'housewarming-hamper',          2),
  ('housewarming-gifts',           'New Home Gift Box',            'new-home-gift-box',            3),
  ('retirement-gifts',             'Retirement Gift Set',          'retirement-gift-set',          1),
  ('retirement-gifts',             'Farewell Hamper',              'farewell-hamper',              2),
  ('retirement-gifts',             'Legacy Gift Box',              'legacy-gift-box',              3),
  ('graduation-gifts',             'Graduation Gift Box',          'graduation-gift-box',          1),
  ('graduation-gifts',             'Achievement Gift Set',         'achievement-gift-set',         2),
  ('graduation-gifts',             'Success Hamper',               'success-hamper',               3),
  ('get-well-soon-gifts',          'Recovery Hamper',              'recovery-hamper',              1),
  ('get-well-soon-gifts',          'Wellness Gift Box',            'wellness-gift-box',            2),
  ('get-well-soon-gifts',          'Care & Comfort Set',           'care-comfort-set',             3),
  ('friendship-gifts',             'Friendship Gift Set',          'friendship-gift-set',          1),
  ('friendship-gifts',             'Best Friend Hamper',           'best-friend-hamper',           2),
  ('friendship-gifts',             'Friendship Keepsake Box',      'friendship-keepsake-box',      3),
  ('valentine-gifts',              'Romantic Gift Box',            'romantic-gift-box',            1),
  ('valentine-gifts',              'Valentine Hamper',             'valentine-hamper',             2),
  ('valentine-gifts',              'Love Celebration Set',         'love-celebration-set',         3),
  ('mothers-day-gifts',            'Mother''s Day Gift Set',       'mothers-day-gift-set',         1),
  ('mothers-day-gifts',            'Mom Hamper',                   'mom-hamper',                   2),
  ('mothers-day-gifts',            'Mother''s Day Surprise Box',   'mothers-day-surprise-box',     3),
  ('fathers-day-gifts',            'Father''s Day Gift Set',       'fathers-day-gift-set',         1),
  ('fathers-day-gifts',            'Dad Hamper',                   'dad-hamper',                   2),
  ('fathers-day-gifts',            'Father''s Day Surprise Box',   'fathers-day-surprise-box',     3),
  ('christmas-gifts',              'Christmas Hamper',             'christmas-hamper',             1),
  ('christmas-gifts',              'Holiday Gift Box',             'holiday-gift-box',             2),
  ('christmas-gifts',              'Festive Celebration Set',      'festive-celebration-set',      3),
  ('new-year-gifts',               'New Year Hamper',              'new-year-hamper',              1),
  ('new-year-gifts',               'Celebration Box',              'celebration-box',              2),
  ('new-year-gifts',               'New Year Gift Set',            'new-year-gift-set',            3),
  ('eid-gifts',                    'Eid Hamper',                   'eid-hamper',                   1),
  ('eid-gifts',                    'Eid Gift Box',                 'eid-gift-box',                 2),
  ('eid-gifts',                    'Eid Celebration Set',          'eid-celebration-set',          3),
  ('diwali-gifts',                 'Diwali Hamper',                'diwali-hamper',                1),
  ('diwali-gifts',                 'Festive Gift Box',             'festive-gift-box',             2),
  ('diwali-gifts',                 'Diwali Celebration Set',       'diwali-celebration-set',       3),
  ('rakhi-gifts',                  'Rakhi Gift Set',               'rakhi-gift-set',               1),
  ('rakhi-gifts',                  'Brother-Sister Gift Box',      'brother-sister-gift-box',      2),
  ('rakhi-gifts',                  'Rakhi Celebration Hamper',     'rakhi-celebration-hamper',     3),
  ('corporate-merchandise',        'Branded Mug',                  'branded-mug',                  1),
  ('corporate-merchandise',        'Branded Notebook',             'branded-notebook',             2),
  ('corporate-merchandise',        'Promotional Gift Set',         'promotional-gift-set',         3),
  ('gift-baskets',                 'Fruit Basket',                 'fruit-basket',                 1),
  ('gift-baskets',                 'Gourmet Basket',               'gourmet-basket',               2),
  ('gift-baskets',                 'Mixed Gift Basket',            'mixed-gift-basket',            3),
  ('surprise-gifts',               'Mystery Gift Box',             'mystery-gift-box',             1),
  ('surprise-gifts',               'Surprise Hamper',              'surprise-hamper',              2),
  ('surprise-gifts',               'Reveal Gift Set',              'reveal-gift-set',              3),
  ('collectible-gifts',            'Collectible Figurine',       'collectible-figurine',         1),
  ('collectible-gifts',            'Memorabilia Item',             'memorabilia-item',             2),
  ('collectible-gifts',            'Limited Edition Collectible',  'limited-edition-collectible',  3),
  ('pet-gifts',                    'Pet Toy Set',                  'pet-toy-set',                  1),
  ('pet-gifts',                    'Pet Care Gift Box',            'pet-care-gift-box',            2),
  ('pet-gifts',                    'Pet Treat Hamper',             'pet-treat-hamper',             3),
  ('travel-gifts',                 'Travel Kit',                   'travel-kit',                   1),
  ('travel-gifts',                 'Travel Accessories Set',       'travel-accessories-set',       2),
  ('travel-gifts',                 'Journey Gift Box',             'journey-gift-box',             3),
  ('tech-gifts',                   'Wireless Earbuds',             'wireless-earbuds',             1),
  ('tech-gifts',                   'Smart Gadget Gift Set',        'smart-gadget-gift-set',        2),
  ('tech-gifts',                   'Tech Accessories Hamper',      'tech-accessories-hamper',      3),
  ('fashion-accessories-gifts',    'Wallet',                       'wallet',                       1),
  ('fashion-accessories-gifts',    'Handbag',                      'handbag',                      2),
  ('fashion-accessories-gifts',    'Sunglasses',                   'sunglasses',                   3),
  ('kitchen-dining-gifts',         'Dinnerware Set',               'dinnerware-set',               1),
  ('kitchen-dining-gifts',         'Kitchen Gift Box',             'kitchen-gift-box',             2),
  ('kitchen-dining-gifts',         'Dining Essentials Set',        'dining-essentials-set',        3),
  ('books-hobby-gifts',            'Book Set',                     'book-set',                     1),
  ('books-hobby-gifts',            'Hobby Kit',                    'hobby-kit',                    2),
  ('books-hobby-gifts',            'Creative Gift Set',            'creative-gift-set',            3),
  ('wellness-hampers',             'Wellness Hamper',              'wellness-hamper',              1),
  ('wellness-hampers',             'Self-Care Box',                'self-care-box',                2),
  ('wellness-hampers',             'Relaxation Gift Set',          'relaxation-gift-set',          3),
  ('luxury-hampers',               'Premium Luxury Hamper',        'premium-luxury-hamper',        1),
  ('luxury-hampers',               'Executive Hamper',             'executive-hamper',             2),
  ('luxury-hampers',               'Signature Luxury Collection',  'signature-luxury-collection',  3),
  ('snack-hampers',                'Snack Box',                    'snack-box',                    1),
  ('snack-hampers',                'Gourmet Snack Hamper',         'gourmet-snack-hamper',         2),
  ('snack-hampers',                'Party Snack Gift Set',         'party-snack-gift-set',         3),
  ('chocolate-hampers',            'Chocolate Collection Hamper',  'chocolate-collection-hamper',  1),
  ('chocolate-hampers',            'Premium Chocolate Box',      'premium-chocolate-box',        2),
  ('chocolate-hampers',            'Artisan Chocolate Set',        'artisan-chocolate-set',        3),
  ('fruit-baskets',                'Fresh Fruit Basket',           'fresh-fruit-basket',           1),
  ('fruit-baskets',                'Premium Fruit Collection',     'premium-fruit-collection',     2),
  ('fruit-baskets',                'Seasonal Fruit Hamper',        'seasonal-fruit-hamper',        3),
  ('flower-arrangements',          'Floral Arrangement',           'floral-arrangement',           1),
  ('flower-arrangements',          'Floral Basket',                'floral-basket',                2),
  ('flower-arrangements',          'Premium Flower Display',       'premium-flower-display',       3),
  ('gift-sets',                    'Beauty Gift Set',              'beauty-gift-set',              1),
  ('gift-sets',                    'Food Gift Set',                'food-gift-set',                2),
  ('gift-sets',                    'Lifestyle Gift Set',           'lifestyle-gift-set',           3),
  ('keepsakes-souvenirs',          'Souvenir Item',                'souvenir-item',                1),
  ('keepsakes-souvenirs',          'Memory Keepsake',              'memory-keepsake',              2),
  ('keepsakes-souvenirs',          'Commemorative Gift',           'commemorative-gift',           3),
  ('personalized-accessories',     'Customized Keychain',          'customized-keychain',          1),
  ('personalized-accessories',     'Personalized Wallet',          'personalized-wallet',          2),
  ('personalized-accessories',     'Engraved Accessory Set',       'engraved-accessory-set',       3),
  ('event-celebration-supplies',   'Party Decoration Set',         'party-decoration-set',         1),
  ('event-celebration-supplies',   'Celebration Accessories',      'celebration-accessories',      2),
  ('event-celebration-supplies',   'Event Essentials Pack',        'event-essentials-pack',        3)
)
INSERT INTO public.categories (name, slug, parent_id, level, display_order, is_active)
SELECT t.name,
       t.base_slug || '-in-' || l2.slug,
       l2.id,
       3,
       t.display_order,
       true
FROM types t
JOIN l2 ON l2.slug = t.l2_slug
ON CONFLICT (slug) DO NOTHING;

COMMIT;
