import SwiftUI

/// Exact buyer-section colors from web Header / BzeadHomePage (Android BuyerColors.kt).
enum BuyerColors {
    static let headerBg = Color(hex: 0x1E293B)
    static let headerGold = Color(hex: 0xD4AF37)
    static let headerText = Color.white
    static let starFilled = Color(hex: 0xF69931)
    static let starEmpty = Color(hex: 0xD1D5DB)
    static let linkBlue = Color(hex: 0x1F5EA8)
    static let priceRed = Color(hex: 0xCC0C39)
    static let brandNewRed = Color(hex: 0xE11D24)
    static let offerPurple = Color(hex: 0x2F16C7)
    static let buyNowBlue = Color(hex: 0x2F6FE4)
    static let addToCartGray = Color(hex: 0x374151)
    static let shareNavy = Color(hex: 0x0B2A66)
    static let tabDetails = Color(hex: 0x6D28D9)
    static let tabSpecs = Color(hex: 0x0F766E)
    static let tabReviews = Color(hex: 0xEA580C)
    static let textPrimary = Color(hex: 0x0F1111)
    static let textSecondary = Color(hex: 0x565959)
    static let borderGray = Color(hex: 0xD1D5DB)
    static let sectionBg = Color(hex: 0xF0F2F2)
    static let deliveryBg = Color(hex: 0xEEF3FA)
    static let progressOrange = Color(hex: 0xFF6A00)
    static let cartPageBg = Color(hex: 0xEAEDED)
    static let cartBorder = Color(hex: 0xDDDDDD)
    static let cartPrice = Color(hex: 0xB12704)
    static let cartLink = Color(hex: 0x007185)
    static let cartCheckoutYellow = Color(hex: 0xFFD814)
    static let cartCheckoutYellowBorder = Color(hex: 0xFCD200)
    static let cartCheckoutYellowHover = Color(hex: 0xF7CA00)
    static let cartInStockBg = Color(hex: 0xD1FAE5)
    static let cartInStockText = Color(hex: 0x047857)
    static let cartOutOfStockBg = Color(hex: 0xFEE2E2)
    static let cartOutOfStockText = Color(hex: 0xB91C1C)
    static let cartShippingGreen = Color(hex: 0x067D62)
    static let searchGoBlack = Color(hex: 0x000000)
    static let seeMoreBlue = Color(hex: 0x2563EB)
    static let breakdownLink = Color(hex: 0x007185)
}
