
WITH input_data (
  name, description, short_description, brand, country,
  category_slug, sub_category_slug, product_type_slug,
  price, mrp, stock, sku
) AS (
  VALUES
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0001'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0002'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0003'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0004'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0005'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0006'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0007'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0008'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0009'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0010'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0011'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0012'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0013'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0014'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0015'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0016'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0017'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0018'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0019'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0020'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0021'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0022'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0023'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0024'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0025'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0026'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0027'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0028'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0029'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0030'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0031'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0032'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0033'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0034'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0035'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0036'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0037'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0038'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0039'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0040'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0041'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0042'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0043'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0044'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0045'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0046'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0047'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0048'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0049'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0050'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0051'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0052'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0053'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0054'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0055'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0056'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0057'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0058'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0059'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0060'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0061'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0062'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0063'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0064'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0065'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0066'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0067'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0068'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0069'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0070'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0071'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0072'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0073'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0074'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0075'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0076'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0077'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0078'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0079'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0080'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0081'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0082'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0083'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0084'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0085'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0086'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0087'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0088'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0089'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0090'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0091'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0092'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0093'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0094'),
  ('', '', '', '', '', '', '', '', 0::numeric, 0::numeric, 0::integer, 'MKV-0095')
), prepared AS (
  SELECT
    i.*,
    c1.id AS category_id,
    c2.id AS sub_category_id,
    c3.id AS product_type_id
  FROM input_data i
  LEFT JOIN public.categories c1 ON c1.slug = i.category_slug
  LEFT JOIN public.categories c2 ON c2.slug = i.sub_category_slug
  LEFT JOIN public.categories c3 ON c3.slug = i.product_type_slug
), ins AS (
  INSERT INTO public.products (
    seller_id, name, description, short_description,
    category, sub_category, product_type,
    brand, sku, price, mrp, currency, stock,
    image_url, images, videos, highlights, specifications,
    approval_status, is_active, origin_country, default_selling_price,
    item_condition
  )
  SELECT
    'd4b2e915-7dce-4af8-b156-3845e7835c11'::uuid,
    p.name,
    nullif(p.description, ''),
    nullif(p.short_description, ''),
    p.category_id,
    p.sub_category_id,
    p.product_type_id,
    nullif(p.brand, ''),
    p.sku,
    coalesce(p.price,0),
    coalesce(p.mrp,0),
    'INR',
    coalesce(p.stock,0),
    '',
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[],
    '{}'::jsonb,
    'pending',
    false,
    nullif(p.country, ''),
    coalesce(p.price,0),
    'new'
  FROM prepared p
  WHERE NOT EXISTS (
    SELECT 1 FROM public.products x
    WHERE x.seller_id = 'd4b2e915-7dce-4af8-b156-3845e7835c11'::uuid AND x.sku = p.sku
  )
  RETURNING id
)
SELECT
  (SELECT count(*) FROM input_data) AS total_input_rows,
  (SELECT count(*) FROM ins) AS inserted_rows,
  (SELECT count(*) FROM public.products x WHERE x.seller_id = 'd4b2e915-7dce-4af8-b156-3845e7835c11'::uuid AND x.sku LIKE 'MKV-%') AS seller_mkv_rows,
  (SELECT count(*) FROM public.products x WHERE x.seller_id = 'd4b2e915-7dce-4af8-b156-3845e7835c11'::uuid AND x.sku LIKE 'MKV-%' AND x.approval_status='pending' AND x.is_active=false) AS seller_mkv_pending_inactive;
