import Foundation

enum BuyerStrings {
    static let landingBrand = "BZEAD"
    static let homeSearchHint = "Search for products, brands…"
    static let homeSearchGo = "Go"
    static let homeCategoryAll = "All"
    static let homeSearchResults = "Search results"
    static let homeSponsored = "SPONSORED"
    static let homeNoProducts = "No products available right now."
    static let seeMore = "See More"
    static let addedToCart = "Added to cart"
    static let alreadyInCart = "Already In Cart"
    static let addToCart = "Add to Cart"
    static let actionFailed = "Something went wrong. Try again."
    static let locationDetectHint = "Tap to detect delivery location"
    static let locationDetecting = "Detecting location…"
    static let locationPermissionDenied = "Location permission denied. Enable it in Settings."
    static let pressBackAgain = "Press back again to exit"
    static let navHome = "Home"
    static let navOrders = "Orders"
    static let navNotifications = "Notifications"
    static let navProfile = "Profile"
    static let headerLocation = "Delivery location"
    static let headerWishlist = "Wishlist"
    static let headerCart = "Cart"
    static let headerMenu = "Menu"
    static let menuBecomeSeller = "Become a Seller"
    static let menuHelp = "Help & Support"
    static let menuLogout = "Logout"
    static let headerCurrencyLabel = "Currency"
    static let headerTrackOrder = "Track Order"
    static let headerLogoutConfirmTitle = "Confirm Logout"
    static let headerLogoutConfirmBody = "Are you sure you want to log out of your account?"
    static let headerSellerConfirmTitle = "Open Seller Portal?"
    static let headerSellerConfirmBody = "The seller dashboard isn't part of the BZEAD buyer app. We'll open it in your phone's browser at bzead.com/seller."
    static let headerSellerConfirmHint = "You can return to this app any time."
    static let continueLabel = "Continue"
    static let cancel = "Cancel"
    static let save = "Save"
    static let saved = "Saved"
    static let productNotFound = "Product not found"
    static let selectSize = "Select size"
    static let selectColor = "Select color"
    static let selectVariant = "Select size and color"
    static let buyNow = "Buy now"
    static let pdpLoadingPrice = "Loading price…"
    static let pdpInclusiveTaxes = "Inclusive of all taxes"
    static let pdpOutOfStock = "This product is currently out of stock."
    static let pdpCheckingDelivery = "Checking delivery availability…"
    static let pdpDeliveryNotAvailable = "Delivery not available to this location"
    static func pdpDeliveryBy(_ date: String) -> String { "Delivery by \(date)" }
    static let pdpDeliveryAtCheckout = "Delivery details available at checkout"
    static let pdpSelectDeliveryAddress = "Select delivery address"
    static let pdpSavedAddresses = "Saved addresses"
    static let pdpNoReviews = "No reviews yet."
    static let pdpNoReviewsFirst = "No reviews yet. Be the first to review."
    static let pdpPriceUnavailable = "Price unavailable for your region."
    static let pdpSelectDeliveryLocation = "Select delivery location ›"
    static let pdpNoDetails = "No product details available."
    static let pdpSimilarProducts = "Similar Products"
    static let pdpShare = "Share product"
    static let cartEmptyTitle = "Your Cart is Empty"
    static let cartEmptySubtitle = "Add items to your cart to get started with shopping."
    static let cartShoppingCart = "Shopping Cart"
    static func cartItemsCount(_ n: Int) -> String { n == 1 ? "\(n) item in your cart" : "\(n) items in your cart" }
    static let cartSelectAll = "Select all items"
    static let cartDeselectAll = "Deselect all"
    static func cartSelectedCount(_ n: Int) -> String { "\(n) selected" }
    static func cartSoldBy(_ seller: String) -> String { "Sold by: \(seller)" }
    static let cartInStock = "In Stock"
    static let cartOutOfStock = "Out of Stock"
    static let cartDelete = "Delete"
    static let cartMoveWishlist = "Move to Wishlist"
    static let cartMovedWishlist = "Moved to wishlist"
    static let cartSummary = "Cart Summary"
    static func cartSubtotalItems(_ n: Int) -> String { n == 1 ? "Subtotal (\(n) item)" : "Subtotal (\(n) items)" }
    static let cartShippingAtCheckout = "Calculated at checkout"
    static let cartEstimatedTotal = "Estimated Total"
    static let cartProceedCheckout = "Proceed to Checkout →"
    static let cartWaitingPrices = "Waiting for final prices…"
    static let cartSecureCheckout = "🔒 Secure checkout powered by Stripe"
    static let cartContinueShopping = "Continue Shopping"
    static let cartRemoveTitle = "Remove Item"
    static let cartRemoveMessage = "Are you sure you want to remove this item from your cart?"
    static let cartRemoveConfirm = "Remove"
    static let cartPricingFailedTitle = "Unable to Load Prices"
    static let cartPricingFailedMessage = "We're having trouble connecting right now. Your cart items are safe — please refresh to try again."
    static let cartPricingRefresh = "Refresh"
    static let subtotal = "Subtotal"
    static let shipping = "Shipping"
    static let total = "Total"
    static let size = "Size"
    static let color = "Color"
    static let wishlistTitle = "Wishlist"
    static func wishlistItemsSaved(_ n: Int) -> String { "\(n) items saved" }
    static let wishlistTotalValue = "Total Value"
    static let wishlistTotalSavings = "Total Savings"
    static let wishlistItems = "Items"
    static let wishlistViewAdd = "View & Add to Cart"
    static let wishlistRemove = "Remove"
    static let wishlistRemoveTitle = "Remove from Wishlist?"
    static let wishlistRemoveMessage = "This item will be removed from your wishlist."
    static let wishlistRemoveConfirm = "Remove"
    static let wishlistEmptyTitle = "Wishlist Empty"
    static let wishlistEmptyHint = "Start adding items to your wishlist to save them for later."
    static let notificationsTitle = "Notifications"
    static let notificationsMarkAllRead = "Mark all as read"
    static let checkoutShippingTitle = "Shipping Address"
    static let checkoutNewAddress = "+ New Address"
    static func checkoutSavedAddresses(_ n: Int) -> String { "Saved (\(n))" }
    static let checkoutDefaultBadge = "Default"
    static let checkoutContinueReview = "Continue to Review Order"
    static let checkoutSaving = "Saving…"
    static let checkoutRefreshingShipping = "Refreshing Shipping…"
    static let checkoutSelectAddressHint = "Please select an address above to continue"
    static let orderSummary = "Order Summary"
    static let checkoutSavings = "Savings"
    static let checkoutOrderTotal = "Order Total"
    static let checkoutCalculating = "Calculating…"
    static let checkoutShippingFree = "FREE"
    static let checkoutReviewTitle = "Review Items & Delivery"
    static let checkoutChangeAddress = "Change address →"
    static let checkoutProceedPayment = "Proceed to Payment"
    static let checkoutBackCart = "← Back to Cart"
    static let checkoutChooseDeliverySpeed = "CHOOSE DELIVERY SPEED"
    static let checkoutPayOnline = "Pay Online"
    static let checkoutPayCodTab = "Cash on Delivery"
    static let checkoutPaymentMethod = "PAYMENT METHOD"
    static let checkoutStripeSecureNote = "Tap Pay Now to open Stripe's secure payment sheet and enter your card details."
    static func checkoutPayNow(_ amount: String) -> String { "PAY NOW — \(amount)" }
    static let checkoutPayNowGeneric = "PAY NOW"
    static let checkoutProcessing = "Processing…"
    static let checkoutBackReview = "Back to Review"
    static let checkoutCodDescription = "Pay in cash when your order is delivered. No online payment required."
    static func checkoutPlaceCod(_ amount: String) -> String { "Place COD Order — \(amount)" }
    static let payCod = "Place order (Cash on Delivery)"
    static let placingOrder = "Placing order…"
    static let orderPlaced = "Order placed successfully"
    static let orderFailed = "Failed to place order"
    static let paymentFailed = "Payment failed"
    static let stripeNotConfigured = "Card payments are not configured. Add STRIPE_PUBLISHABLE_KEY to Secrets.plist."
    static let noAddresses = "No saved addresses"
    static let addAddress = "Add address"
    static let orderConfirmTitle = "Order Confirmed!"
    static let orderConfirmSubtitle = "Thank you for your purchase. Your order has been successfully placed."
    static let orderConfirmViewOrders = "View All Orders"
    static let orderConfirmContinueShopping = "Continue Shopping"
    static let orderConfirmNeedHelp = "Need Help?"
    static let orderConfirmContactSupport = "Contact Support"
    static let ordersMyOrders = "My Orders"
    static let ordersEmptyTitle = "No orders yet"
    static let ordersEmptySubtitle = "When you place an order, it will appear here."
    static let orderDetail = "Order details"
    static let orderDetailBack = "Back to Orders"
    static let orderNotFound = "Order not found"
    static let profileTitle = "My profile"
    static let settingsTitle = "Settings"
    static let addressesTitle = "My addresses"
    static let writeReviewTitle = "Write a Review"
    static let writeReviewSubmit = "Submit Review"
    static let writeReviewSuccess = "Review submitted"
    static let deleteAccountTitle = "Delete Account"
    static let deleteAccountWarning = "This permanently removes your profile, saved addresses, wishlist, and order history access. This cannot be undone."
    static let deleteAccountConfirm = "Delete Account"
    static let categoryFilters = "Filters"
    static let categoryBackHome = "Back to Home"
    static let categoryNoProducts = "No products found"
    static let categoryTryAgain = "Try Again"
    static let sectionNoProducts = "No Products Found"
    static let sectionNotFound = "Section Not Found"
    static let edit = "Edit"
    static let setDefault = "Set as default"
    static let defaultAddress = "Default"
    static let fullName = "Full name"
    static let phone = "Phone"
    static let email = "Email"
    static let street = "Street address"
    static let street2 = "Apartment, suite, etc."
    static let city = "City"
    static let state = "State"
    static let postalCode = "Postal code"
    static let country = "Country"
    static func checkoutItemsMany(_ n: Int) -> String { "Items (\(n))" }
    static func checkoutItemCount(_ n: Int) -> String { n == 1 ? "\(n) item" : "\(n) items" }
    static let checkoutViewDetails = "View details"
    static let checkoutCod = "Cash on Delivery"
    static let checkoutCodAvailable = "Available"
    static let checkoutCodUnavailable = "Not available"
    static let checkoutNotServiceable = "Not serviceable"
    static func checkoutMinimumOrder(_ amount: String) -> String { "Minimum order: \(amount)" }
    static let checkoutMinimumOrderHint = "Add more items to meet the minimum order value."
    static let checkoutAccepted = "We accept"
    static let checkoutSslStripe = "Secure checkout via Stripe SSL"
    static let shippingStandard = "Standard"
    static let shippingPremium = "Premium"
    static let shippingExpress = "Express"
    static let checkoutBestValue = "Best Value"
    static let checkoutPriority = "Priority"
    static let checkoutFastest = "Fastest"
    static let checkoutSelectedBadge = "Selected"
    static func checkoutEstDelivery(_ label: String) -> String { "Est. delivery: \(label)" }
    static func checkoutEstimatedDeliveryLabel(_ label: String) -> String { "Estimated delivery: \(label)" }
    static func checkoutQtyLabel(_ qty: Int) -> String { "Qty: \(qty)" }
    static let checkoutDeliveryCalculating = "Calculating delivery…"
    static let checkoutFreeDelivery = "Free delivery"
    static let checkoutDeliveryIncluded = "Delivery included"
    static let checkoutConfigUnavailable = "Shipping unavailable"
    static let cartEmpty = "Your cart is empty"
    static let cartSelectItemCheckout = "Select at least one item to checkout"
    static let cartOutOfStockCheckout = "Remove out-of-stock items before checkout"
    static let wishlistInStock = "In Stock"
    static let wishlistLowStock = "Low Stock"
    static let wishlistOutOfStock = "Out of Stock"
    static let wishlistContinueShopping = "Continue Shopping"

    // Category / section catalog
    static func categoryResults(_ count: Int) -> String { "\(count) results" }
    static let categoryAll = "All"
    static func categoryAllNamed(_ name: String) -> String { "All \(name)" }
    static let categoryDepartment = "Department"
    static let categoryPrice = "Price"
    static func categoryPriceMin(_ amount: String) -> String { "Min: \(amount)" }
    static func categoryPriceMax(_ amount: String) -> String { "Max: \(amount)" }
    static let categoryCustomerReview = "Customer Review"
    static let categoryRatingUp = "& Up"
    static let categoryInStock = "In Stock Only"
    static let categoryBrand = "Brand"
    static let categoryReset = "Reset"
    static let categoryShowResults = "Show Results"
    static let categorySortFeatured = "Sort: Featured"
    static let categorySortPriceLow = "Price: Low to High"
    static let categorySortPriceHigh = "Price: High to Low"
    static let categorySortRating = "Avg. Customer Review"
    static let categorySortNewest = "Newest Arrivals"
    static func categoryProductCount(_ count: Int) -> String { "\(count) products" }
    static func categoryOtherIn(_ name: String) -> String { "Other in \(name)" }
    static let categoryNoProductsHint = "Try adjusting your filters or browse a different category."
    static let categoryClearFilters = "Clear Filters"
    static let categoryNotFound = "Category Not Found"
    static let categoryNotFoundHint = "The category you're looking for doesn't exist or has been removed."
    static let categoryErrorTitle = "Something went wrong"
    static let categoryLoadError = "Failed to load products. Please try again."
    static let sectionSortFeatured = "Featured"
    static let sectionSortBy = "Sort By"
    static let sectionCategoryFilter = "Category"
    static let sectionAllCategories = "All Categories"
    static func sectionFiltersCount(_ n: Int) -> String { "Filters (\(n))" }
    static let sectionNoProductsHint = "Try adjusting your filters to find what you're looking for."
    static let sectionNotFoundHint = "The product section you're looking for doesn't exist."

    // Orders
    static let ordersSearchHint = "Search by Order ID, Product Name, or Tracking #"
    static let ordersNoMatch = "No matching orders"
    static let ordersNoCategory = "No orders in this category"
    static func ordersCountLabel(_ n: Int) -> String { "\(n) orders" }
    static let ordersCopy = "Copy"
    static let ordersCopied = "Copied!"
    static let ordersTrack = "Track My Order"
    static let ordersCancelTitle = "Cancel Order"
    static func ordersCancelOrderLabel(_ number: String) -> String { "Order: \(number)" }
    static let ordersCancelHint = "Reason for cancellation *"
    static let ordersCancelConfirm = "Cancel Order"
    static let ordersCancelling = "Cancelling…"
    static let ordersCancelSuccess = "Order cancelled successfully"
    static let ordersCancelFailed = "Failed to cancel order"
    static let ordersRateReview = "Rate & Review"
    static let ordersReturnRefund = "Return / Refund"
    static let ordersReturnTitle = "Request Return / Refund"
    static let ordersReturnDetails = "Additional details"
    static let ordersReturnSubmit = "Submit Return"
    static let ordersReturnSubmitting = "Submitting…"
    static let ordersReturnSuccess = "Return request submitted"
    static let ordersReturnFailed = "Failed to submit return"
    static let ordersInvoice = "Invoice"
    static let ordersRequestRefund = "Request Refund"
    static let ordersRefundTitle = "Request Refund"
    static func ordersRefundAmount(_ amount: String) -> String { "Refund amount: \(amount)" }
    static let ordersRefundReason = "Reason for refund *"
    static let ordersRefundSubmit = "Submit Refund Request"
    static let ordersRefundSubmitting = "Submitting…"
    static let ordersRefundSuccess = "Refund request submitted"
    static let ordersRefundFailed = "Failed to submit refund request"
    static func ordersDeliveredOn(_ date: String) -> String { "Delivered on \(date)" }
    static let ordersPaid = "PAID"
    static func ordersSeller(_ name: String) -> String { "Seller: \(name)" }
    static func ordersMoreItems(_ n: Int) -> String { "+\(n) more item(s)" }
    static let ordersProductFallback = "Product"
    static let ordersBuyAgain = "Buy Again"
    static let ordersBuyAgainLoading = "Adding…"
    static let ordersBuyAgainSuccess = "Items added to cart"
    static let ordersBuyAgainUnavailable = "Some items are no longer available"
    static let ordersBuyAgainFailed = "Failed to add items to cart"
    static let ordersNeedHelp = "Need Help"

    // Order confirmation
    static let orderConfirmSubtitle = "Thank you for your purchase. Your order has been successfully placed."
    static let orderConfirmNumberLabel = "Order Number"
    static func orderConfirmEmailSent(_ email: String) -> String { "Confirmation email sent to \(email)" }
    static let orderConfirmStatusTitle = "Order Status"
    static func orderConfirmPlacedOn(_ date: String) -> String { "Placed on \(date)" }
    static let orderConfirmDetailsTitle = "Order Details"
    static func orderConfirmQty(_ qty: Int) -> String { "Quantity: \(qty)" }
    static let orderConfirmShippingAddress = "Shipping Address"
    static let orderConfirmPaymentInfo = "Payment Information"
    static let orderConfirmPaymentStatus = "Payment Status"
    static let orderConfirmTransactionId = "Transaction ID"
    static let orderConfirmTotalPaid = "Total Paid"
    static let orderConfirmNeedHelpBody = "If you have any questions about your order, please contact our support team through the Contact page."
    static let orderConfirmPendingTitle = "Payment Received & Your order is creating"
    static let orderConfirmPendingBody = "Your payment is successful. We are creating your order now. Please keep this page open for a moment."
    static let orderConfirmSupportTitle = "Contact Support"
    static let orderConfirmSupportWhatsapp = "WhatsApp: +44 7555 394997"
    static let orderConfirmGoOrders = "Go To My Orders"
    static let items = "Items"
    static let payment = "Payment"

    // Order detail / tracking
    static func orderDetailPlaced(_ date: String) -> String { "Placed on \(date)" }
    static let orderDetailTabItems = "Items"
    static let orderDetailTabTracking = "Tracking"
    static let orderDetailTabInvoice = "Invoice"
    static let orderDetailNoItems = "No items found"
    static let orderDetailNoTracking = "Tracking will appear once your order is shipped"
    static let orderTrackingOnTheWay = "Your order is on the way"
    static let orderTrackingPreparing = "We are preparing your order"
    static let orderTrackingCancelled = "This order was cancelled"
    static let orderTrackingStepDelivered = "Delivered"
    static let orderTrackingShipmentDetails = "Shipment details"
    static let orderTrackingCourier = "Courier partner"
    static let orderTrackingAwb = "Tracking ID"
    static let orderTrackingCopy = "Copy"
    static let orderTrackingCopied = "Tracking ID copied"
    static let orderTrackingDeliveryAddress = "Delivery address"
    static let orderTrackingCurrent = "Current status"
    static let orderDetailSubtotal = "Subtotal"
    static let orderDetailPlatformFee = "Platform fee"
    static let orderDetailTotal = "Total"
    static let orderDetailWriteReview = "Write Review"
    static let orderDetailInvoiceNumber = "Invoice Number"
    static let orderDetailPlacedLabel = "Order Date"
    static let orderDetailInvoiceNote = "Invoice PDF download is available on the web store."

    // Notifications
    static let notificationsFilterAll = "All"
    static let notificationsFilterUnread = "Unread"
    static let notificationsFilterRead = "Read"
    static let notificationsCatAll = "All updates"
    static let notificationsCatOrders = "Orders"
    static let notificationsCatReturns = "Returns"
    static let notificationsCatOffers = "Offers & info"
    static let notificationsEmptyTitle = "No notifications"
    static let notificationsEmptyHint = "Order and delivery updates will show up here."
    static let notificationsClearFilters = "Clear filters"

    // Profile
    static let profileSubtitle = "Manage your account and preferences"
    static let profileLoginSecurity = "Login and Security"
    static let profileEmailHint = "Email address cannot be changed"
    static let profileNotSet = "Not set"
    static let profileChangePassword = "Change Password"
    static let profileDownloadData = "Download My Data"
    static let profileDeleteAccount = "Delete Account"
    static let deleteAccountReasonLabel = "Why are you leaving?"
    static let deleteAccountReasonHint = "Select a reason"
    static let deleteAccountReasonRequired = "Please select a reason"
    static let deleteAccountPasswordLabel = "Confirm your password"
    static let deleteAccountPasswordRequired = "Password is required"
    static let deleteAccountSuccess = "Your account has been deleted"
    static let deleteReasonNoLongerNeed = "I no longer need this account"
    static let deleteReasonPrivacy = "Privacy concerns"
    static let deleteReasonTooManyEmails = "Too many emails or notifications"
    static let deleteReasonBadExperience = "I had a bad experience"
    static let deleteReasonOther = "Other"
    static let profileLogoutDevice = "Log out of this device"
    static let profileLogoutConfirmTitle = "Log out?"
    static let profileLogoutConfirmBody = "You will be signed out of this device."
    static let profileMyAddresses = "My Addresses"
    static let profileAddAddress = "Add New Address"
    static let profileNoAddresses = "No saved addresses"
    static let profileNoAddressesHint = "Add a delivery address for faster checkout"
    static let profileManageAddresses = "Manage Addresses"
    static let profileLegal = "Legal"
    static let profileSupport = "Support"
    static let profilePrivacyPolicy = "Privacy Policy"
    static let profileTermsOfService = "Terms of Service"
    static let profileShippingPolicy = "Shipping Policy"
    static let profileRefundPolicy = "Refund Policy"
    static let profileTermsAndConditions = "Terms & Conditions"
    static let profileAboutUs = "About Us"
    static let profileContactUs = "Contact Us"

    // Settings
    static let settingsSubtitle = "Manage your account preferences"
    static let settingsSaveChanges = "Save Changes"
    static let settingsSavePreferences = "Save Preferences"
    static let settingsCurrentPassword = "Current password"
    static let settingsConfirmPassword = "Confirm new password"
    static let settingsCurrentRequired = "Current password is required"
    static let settingsPasswordMismatch = "Passwords do not match"
    static let profileTab = "Profile"
    static let securityTab = "Security"
    static let notificationsTab = "Notifications"
    static let newPassword = "New password"
    static let updatePassword = "Update password"
    static let passwordTooShort = "Password must be at least 8 characters"
    static let passwordUpdated = "Password updated"
    static let emailNotifications = "Email notifications"
    static let orderUpdates = "Order updates"
    static let promotions = "Promotions"

    // Addresses
    static let addressesSubtitle = "Manage your delivery addresses"
    static let addressesEmptyTitle = "No addresses added yet"
    static let addressesEmptyHint = "Add your first delivery address"
    static let addressesAddFirst = "Add Your First Address"
    static let addressesDeleteTitle = "Delete address?"
    static let addressesDeleteMessage = "This address will be permanently removed."
    static let addressesDeleteConfirm = "Delete"
    static let addressesDeliveryNotes = "Delivery notes"

    // Write review
    static let writeReviewSubtitle = "Share your experience with this product"
    static let writeReviewLoadError = "Unable to Load Product"
    static let writeReviewBenefits = "What did you like? (optional)"
    static let writeReviewTerms = "I agree that this review is based on my genuine experience. False reviews may result in account suspension."
    static let writeReviewDuplicate = "You have already reviewed this product"
    static let writeReviewRating = "Overall rating"
    static let writeReviewHeading = "Review title"
    static let writeReviewComment = "Your review"
    static let writeReviewRatingPoor = "Poor"
    static let writeReviewRatingFair = "Fair"
    static let writeReviewRatingGood = "Good"
    static let writeReviewRatingVeryGood = "Very Good"
    static let writeReviewRatingExcellent = "Excellent"
}
